---
name: Build and Push

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build image
        run: |
          docker build -t iypetrov/avalon-rest:${{ github.ref_name }} .

      - name: Tag & Push to GHCR
        run: |
          docker tag iypetrov/avalon-rest:${{ github.ref_name }} ghcr.io/iypetrov/avalon-rest:${{ github.ref_name }}
          docker push ghcr.io/iypetrov/avalon-rest:${{ github.ref_name }}

  update-image:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger update image 
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "avalonpharma/infra"
          event-type: update-image
          client-payload: |
            {
              "image_name": "ghcr.io/iypetrov/avalon-rest",
              "image_tag": "${{ github.ref_name }}",
              "commit_url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            }
